version: '1.3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 80:80
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16.0
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=USR
    expose:
      - 5432
    restart: always
